services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"

  app:
    build:
      context: ./app
    container_name: python_app
    depends_on:
      - redis
    environment:
      - ENTRY:$ENTRY
    volumes:
      - ./app:/app
      - ./data:/data
    command: python -m app.main
