version: '3.9'

services:
  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ./redis_data:/data
    ports:
      - "6379:6379"

  app:
    build:
      context: ./app
    container_name: python_app
    depends_on:
      - redis
    volumes:
      - ./app:/app
      - ./data:/data
    environment:
      - REDIS_URL=redis://redis:6379/2
    command: python main.py
